site_name: Brainy Help
nav:
  - Getting Started: index.md
  - App Components:
    - app-components/sidebar-and-navigation.md
    - app-components/home.md
    - app-components/editor.md
    - app-components/search-and-find.md
    - app-components/reviewer.md
  - Settings & Data:
    - settings-and-data/settings.md
    - settings-and-data/cloud-sync.md
    - settings-and-data/automatic-backup.md
theme: 
  name: readthedocs
